import { Device, DeviceStatus } from './device';

export const DEVICES: Device[] = [
  {
    name: 'Device 4',
    devui: '#000004',
    reading: 19,
    incomingDate: getDateWithMinutesOffset(-3),
    max: 20,
    batteryLevel: 47,
    signalStrength: 8,
    status: DeviceStatus.NoData,
  },
  {
    name: 'Device 1',
    devui: '#000001',
    min: -100,
    max: 100,
    batteryLevel: 92,
    signalStrength: 8,
    status: DeviceStatus.NoData,
  },
  {
    name: 'Device 10',
    devui: '#000010',
    reading: 1,
    incomingDate: new Date(),
    min: 0,
    max: 200,
    batteryLevel: 98,
    signalStrength: 1,
    status: DeviceStatus.Ok,
  },
  {
    name: 'Device 2',
    devui: '#000002',
    reading: -5,
    incomingDate: new Date(),
    min: 0,
    max: 100,
    batteryLevel: 67,
    signalStrength: 10,
    status: DeviceStatus.Alarm,
  },
  {
    name: 'Device 5',
    devui: '#000005',
    reading: 16,
    incomingDate: getDateWithMinutesOffset(-1),
    min: 0,
    max: 10,
    batteryLevel: 26,
    signalStrength: 3,
    status: DeviceStatus.Alarm,
  },
  {
    name: 'Device 3',
    devui: '#000003',
    batteryLevel: 30,
    signalStrength: 9,
    status: DeviceStatus.NoData,
  },
  {
    name: 'Device 6',
    devui: '#000006',
    reading: -4,
    incomingDate: new Date(),
    min: -50,
    batteryLevel: 81,
    signalStrength: 5,
    status: DeviceStatus.Ok,
  },
  {
    name: 'Device 7',
    devui: '#000007',
    min: 0,
    max: 100,
    batteryLevel: 16,
    signalStrength: 7,
    status: DeviceStatus.NoData,
  },
  {
    name: 'Device 8',
    devui: '#000008',
    reading: 2,
    incomingDate: getDateWithMinutesOffset(-4),
    min: 0,
    max: 50,
    batteryLevel: 65,
    signalStrength: 2,
    status: DeviceStatus.NoData,
  },
  {
    name: 'Device 9',
    devui: '#000009',
    reading: 11,
    incomingDate: new Date(),
    batteryLevel: 72,
    signalStrength: 9,
    status: DeviceStatus.Ok,
  },
  {
    name: 'Device 11',
    devui: '#000011',
    max: 150,
    batteryLevel: 25,
    signalStrength: 4,
    status: DeviceStatus.NoData,
  },
  {
    name: 'Device 12',
    devui: '#000012',
    reading: -1,
    incomingDate: getDateWithMinutesOffset(-1),
    min: 0,
    max: 150,
    batteryLevel: 57,
    signalStrength: 6,
    status: DeviceStatus.Alarm,
  },
  {
    name: 'Device 13',
    devui: '#000013',
    reading: -9,
    incomingDate: getDateWithMinutesOffset(-10),
    min: -5,
    max: 500,
    batteryLevel: 100,
    signalStrength: 5,
    status: DeviceStatus.Alarm,
  },
  {
    name: 'Device 14',
    devui: '#000014',
    reading: 5,
    incomingDate: getDateWithMinutesOffset(-7),
    min: 0,
    max: 1000,
    batteryLevel: 6,
    signalStrength: 8,
    status: DeviceStatus.NoData,
  },
  {
    name: 'Device 15',
    devui: '#000015',
    reading: 2,
    incomingDate: new Date(),
    min: 0,
    max: 100,
    batteryLevel: 52,
    signalStrength: 10,
    status: DeviceStatus.Ok,
  },
];

function getDateWithMinutesOffset(minutesOffset: number): Date {
  const currentDate = new Date();
  currentDate.setMinutes(currentDate.getMinutes() + minutesOffset);
  return currentDate;
}
